n = input('Digite algo: ')
print (type(n))
print('É somente um número?', n.isnumeric())
print('É uma letra, número ou palavra?', n.isalnum())
print('É somente letras ou palavras?', n.isalpha())
print('É tudo maiúsculo?', n.isupper())
print('É decimal?', n.isdecimal())
print('É somente dígito?', n.isdigit())
print('É tudo minúsculo?', n.islower())
